language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

#before_script:
#  - composer self-update
#  - composer install --prefer-source --no-interaction --dev

script: cd .dev/tests/bin/ && ./phpunit_run_all.sh

# script: cd .dev/tests/ && phpunit -d memory_limit=1024M --configuration phpunit.xml ./
#  - cd .dev/tests/ && phpunit --configuration phpunit.xml --coverage-text ./
#  - cd .dev/tests/ && phpunit --configuration phpunit.xml ./

matrix:
#  allow_failures:
#    - php: 5.6
#    - php: hhvm
  fast_finish: true

#after_script:
#  - php ./bin/coveralls -v
